Escape timestamps for fields and tags
influxdata/influxdb-client-ruby pull request #131
Opened 2023-11-13 16:31 UTC by rubhanazeem

Closes #

## Proposed Changes

_Briefly describe your proposed changes:_ Timestamps present in fields and tags are not converted into integers. They should be converted. This PR handles that and converts timestamps from tags and fields into integers. This change is required for [influxdb-rails 2.0](https://github.com/influxdata/influxdb-rails).

## Checklist

- [x] CHANGELOG.md updated
- [x] Rebased/mergeable
- [x] A test has been added if appropriate
- [ ] `rake test` completes successfully
- [x] Commit messages are [conventional](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Sign [CLA](https://www.influxdata.com/legal/cla/) (if not already signed)

2023-11-14 11:23 UTC, bednar requested changes
Hi @rubhanazeem,

Thank you for your PR! 👍

Could you please update the `CHANGELOG.md` with a brief description of your changes? Also, since this PR introduces some minor breaking changes, kindly update the major version of the client to `3.0.0` in `lib/influxdb2/client/version.rb`.

Thanks again for your contribution!

2023-11-14 12:13 UTC, bednar requested changes
Please also rebase your sources with the `master` branch. The `master` branch has an updated `CI` configuration with important fixes.

2023-11-17 09:41 UTC, rubhanazeem commented
Hi @bednar, I've updated the major version but it's not yet available on git that's why it's failing. Could you please have a look at this?

2023-11-18 09:16 UTC, bednar commented
@rubhanazeem I will take a look, thanks again for your PR

2023-11-20 09:13 UTC, bednar approved these changes
LGTM 🚀

2023-11-20 09:14 UTC, merged